FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --frozen-lockfile

# Install TypeScript and nodemon globally
RUN npm install -g typescript nodemon

COPY . .

# Expose the port for development (default 3000)
EXPOSE 3000

# Run the app in development mode with nodemon (hot-reloading)
CMD ["npm", "run", "start:dev"]
