import { Router } from 'express';
import { generateContent } from '../handlers/generateContent';
const router = Router();

/**
 * @openapi
 * /api/generate/text:
 *   post:
 *     summary: Generate content using the Gemini AI model
 *     description: Send a prompt to the Gemini AI model and generate text based on the prompt.
 *     tags:
 *       - Content Generation
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               prompt:
 *                 type: string
 *                 description: The text prompt for the AI model.
 *                 example: "List a few popular cookie recipes using this JSON schema:\n\nRecipe = {'recipeName': string}\nReturn: Array<Recipe>"
 *               topK:
 *                 type: integer
 *                 description: The number of top results to return. Defaults to 5 if not provided.
 *                 example: 3
 *             required:
 *               - prompt
 *     responses:
 *       200:
 *         description: Successfully generated content
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 generatedText:
 *                   type: string
 *                   description: The content generated by the AI model.
 *                   example: "1. Chocolate Chip Cookies\n2. Oatmeal Raisin Cookies\n3. Peanut Butter Cookies"
 *       400:
 *         description: Invalid input
 *       500:
 *         description: Internal server error
 */
router.post("/text", generateContent);

export default router;
